
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author imabeliever
 */
public class home extends javax.swing.JFrame {
    public int z=0;

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        ButtNewB.setVisible(false);
        ButnUpdateBuy.setVisible(false);
        ButnBuyerdet.setVisible(false);
        butndeletebuy.setVisible(false);
        Butnnewprod.setVisible(false);
        ButnProductdet.setVisible(false);
        Butndeleteprod.setVisible(false);
        butnbilling.setVisible(false);
        buttonlogout.setVisible(false);
        buttonclose.setVisible(false);
        Butnupdateprod.setVisible(false);
        
        newBuy.setVisible(false);
        Updatebuy.setVisible(false);
        buyerdetail.setVisible(false);
        deletebuy.setVisible(false);
        NewProd.setVisible(false);
        Updateprod.setVisible(false);
        deleteprod.setVisible(false);
        bill.setVisible(false);
        logout.setVisible(false);
        closeapp.setVisible(false);
        productdetail.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ButtNewB = new javax.swing.JButton();
        ButnUpdateBuy = new javax.swing.JButton();
        ButnBuyerdet = new javax.swing.JButton();
        butndeletebuy = new javax.swing.JButton();
        Butnnewprod = new javax.swing.JButton();
        ButnProductdet = new javax.swing.JButton();
        Butndeleteprod = new javax.swing.JButton();
        butnbilling = new javax.swing.JButton();
        buttonlogout = new javax.swing.JButton();
        buttonclose = new javax.swing.JButton();
        newBuy = new javax.swing.JLabel();
        Updatebuy = new javax.swing.JLabel();
        buyerdetail = new javax.swing.JLabel();
        deletebuy = new javax.swing.JLabel();
        NewProd = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        deleteprod = new javax.swing.JLabel();
        bill = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        closeapp = new javax.swing.JLabel();
        Butnupdateprod = new javax.swing.JButton();
        Updateprod = new javax.swing.JLabel();
        productdetail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/control hide and show.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ButtNewB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new buyer.png"))); // NOI18N
        ButtNewB.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ButtNewBComponentShown(evt);
            }
        });
        ButtNewB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtNewBActionPerformed(evt);
            }
        });

        ButnUpdateBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Update buyer.png"))); // NOI18N
        ButnUpdateBuy.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ButnUpdateBuyComponentShown(evt);
            }
        });
        ButnUpdateBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButnUpdateBuyActionPerformed(evt);
            }
        });

        ButnBuyerdet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buyer Details.png"))); // NOI18N
        ButnBuyerdet.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ButnBuyerdetComponentShown(evt);
            }
        });
        ButnBuyerdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButnBuyerdetActionPerformed(evt);
            }
        });

        butndeletebuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete buyer.png"))); // NOI18N
        butndeletebuy.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                butndeletebuyComponentShown(evt);
            }
        });
        butndeletebuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butndeletebuyActionPerformed(evt);
            }
        });

        Butnnewprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new product.png"))); // NOI18N
        Butnnewprod.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ButnnewprodComponentShown(evt);
            }
        });
        Butnnewprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButnnewprodActionPerformed(evt);
            }
        });

        ButnProductdet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details product.png"))); // NOI18N
        ButnProductdet.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ButnProductdetComponentShown(evt);
            }
        });
        ButnProductdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButnProductdetActionPerformed(evt);
            }
        });

        Butndeleteprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete product.png"))); // NOI18N
        Butndeleteprod.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ButndeleteprodComponentShown(evt);
            }
        });
        Butndeleteprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButndeleteprodActionPerformed(evt);
            }
        });

        butnbilling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing.png"))); // NOI18N
        butnbilling.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                butnbillingComponentShown(evt);
            }
        });
        butnbilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butnbillingActionPerformed(evt);
            }
        });

        buttonlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        buttonlogout.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                buttonlogoutComponentShown(evt);
            }
        });
        buttonlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonlogoutActionPerformed(evt);
            }
        });

        buttonclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        buttonclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncloseActionPerformed(evt);
            }
        });

        newBuy.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        newBuy.setText("New Buyer");

        Updatebuy.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        Updatebuy.setText("Update Buyer");

        buyerdetail.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        buyerdetail.setText("Buyer details");

        deletebuy.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        deletebuy.setText("Delete buyer");

        NewProd.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        NewProd.setText("New Product");

        deleteprod.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        deleteprod.setText("Delete Product");

        bill.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        bill.setText("Billing");

        logout.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        logout.setText("Logout");

        closeapp.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        closeapp.setText("Close Application");

        Butnupdateprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update product.png"))); // NOI18N
        Butnupdateprod.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ButnupdateprodComponentShown(evt);
            }
        });
        Butnupdateprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButnupdateprodActionPerformed(evt);
            }
        });

        Updateprod.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        Updateprod.setText("Update product");

        productdetail.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        productdetail.setText("Product details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtNewB)
                    .addComponent(newBuy))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButnUpdateBuy)
                    .addComponent(Updatebuy))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButnBuyerdet)
                    .addComponent(buyerdetail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butndeletebuy)
                    .addComponent(deletebuy))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewProd)
                    .addComponent(Butnnewprod))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Butnupdateprod)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Updateprod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButnProductdet)
                    .addComponent(productdetail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Butndeleteprod)
                    .addComponent(deleteprod))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butnbilling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonlogout)
                    .addComponent(logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(closeapp)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonclose)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonclose, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonlogout)
                    .addComponent(butnbilling)
                    .addComponent(Butndeleteprod)
                    .addComponent(ButnProductdet)
                    .addComponent(Butnnewprod)
                    .addComponent(butndeletebuy)
                    .addComponent(ButnBuyerdet)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtNewB)
                        .addComponent(ButnUpdateBuy))
                    .addComponent(Butnupdateprod))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newBuy)
                            .addComponent(Updatebuy)
                            .addComponent(buyerdetail)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(deletebuy)
                                .addComponent(NewProd))
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Updateprod))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productdetail)
                            .addComponent(deleteprod)
                            .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(closeapp)
                            .addComponent(logout))))
                .addContainerGap(639, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttoncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncloseActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do You really want to Exit","Select",JOptionPane.YES_NO_OPTION);
        if(a == 0)
           System.exit(0);
    }//GEN-LAST:event_buttoncloseActionPerformed

    private void buttonlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonlogoutActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do You really want to Logout","Select",JOptionPane.YES_NO_OPTION);
        if(a == 0){
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_buttonlogoutActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        if(z == 0){
            try{
                Thread.sleep(100);
                ButtNewB.setVisible(true);
                newBuy.setVisible(true);
            }
            catch(Exception e){
            }
                
        }
        else{
            
        ButtNewB.setVisible(false);
        ButnUpdateBuy.setVisible(false);
        ButnBuyerdet.setVisible(false);
        butndeletebuy.setVisible(false);
        Butnnewprod.setVisible(false);
        ButnProductdet.setVisible(false);
        Butndeleteprod.setVisible(false);
        butnbilling.setVisible(false);
        buttonlogout.setVisible(false);
        buttonclose.setVisible(false);
        Butnupdateprod.setVisible(false);
        
        newBuy.setVisible(false);
        Updatebuy.setVisible(false);
        buyerdetail.setVisible(false);
        deletebuy.setVisible(false);
        NewProd.setVisible(false);
        Updateprod.setVisible(false);
        deleteprod.setVisible(false);
        bill.setVisible(false);
        logout.setVisible(false);
        closeapp.setVisible(false);
        productdetail.setVisible(false);
        z = 0;
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void ButtNewBComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ButtNewBComponentShown
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(100);
                ButnUpdateBuy.setVisible(true);
                Updatebuy.setVisible(true);
            }
            catch(Exception e){
            }
                
        }
        
        
    }//GEN-LAST:event_ButtNewBComponentShown

    private void ButtNewBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtNewBActionPerformed
        // TODO add your handling code here:
        new NewBuyer().setVisible(true);
    }//GEN-LAST:event_ButtNewBActionPerformed

    private void ButnUpdateBuyComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ButnUpdateBuyComponentShown
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(100);
                ButnBuyerdet.setVisible(true);
                buyerdetail.setVisible(true);
            }
            catch(Exception e){
            }
                
        }
    }//GEN-LAST:event_ButnUpdateBuyComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButnBuyerdetComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ButnBuyerdetComponentShown
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(100);
                deletebuy.setVisible(true);
                butndeletebuy.setVisible(true);
            }
            catch(Exception e){
            }
                
        }
    }//GEN-LAST:event_ButnBuyerdetComponentShown

    private void butndeletebuyComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_butndeletebuyComponentShown
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(100);
                Butnnewprod.setVisible(true);
                NewProd.setVisible(true);
            }
            catch(Exception e){
            }
                
        }
    }//GEN-LAST:event_butndeletebuyComponentShown

    private void ButnnewprodComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ButnnewprodComponentShown
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(100);
                Butnupdateprod.setVisible(true);
                Updateprod.setVisible(true);
            }
            catch(Exception e){
            }
                
        }
    }//GEN-LAST:event_ButnnewprodComponentShown

    private void ButnupdateprodComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ButnupdateprodComponentShown
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(100);
                ButnProductdet.setVisible(true);
                productdetail.setVisible(true);
            }
            catch(Exception e){
            }
                
        }
    }//GEN-LAST:event_ButnupdateprodComponentShown

    private void ButnProductdetComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ButnProductdetComponentShown
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(100);
                Butndeleteprod.setVisible(true);
                deleteprod.setVisible(true);
            }
            catch(Exception e){
            }
                
        }
    }//GEN-LAST:event_ButnProductdetComponentShown

    private void ButndeleteprodComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ButndeleteprodComponentShown
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(100);
                butnbilling.setVisible(true);
                bill.setVisible(true);
            }
            catch(Exception e){
            }
                
        }
    }//GEN-LAST:event_ButndeleteprodComponentShown

    private void butnbillingComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_butnbillingComponentShown
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(100);
                buttonlogout.setVisible(true);
                logout.setVisible(true);
            }
            catch(Exception e){
            }
                
        }
    }//GEN-LAST:event_butnbillingComponentShown

    private void buttonlogoutComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_buttonlogoutComponentShown
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(100);
                buttonclose.setVisible(true);
                closeapp.setVisible(true);
                z=1;
            }
            catch(Exception e){
            }
                
        }
    }//GEN-LAST:event_buttonlogoutComponentShown

    private void ButnUpdateBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButnUpdateBuyActionPerformed
        // TODO add your handling code here:
        new UpdateBuyer().setVisible(true);
    }//GEN-LAST:event_ButnUpdateBuyActionPerformed

    private void ButnBuyerdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButnBuyerdetActionPerformed
        // TODO add your handling code here:
        new BuyerDetails().setVisible(true);
    }//GEN-LAST:event_ButnBuyerdetActionPerformed

    private void butndeletebuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butndeletebuyActionPerformed
        // TODO add your handling code here:
        new DeleteBuyer().setVisible(true);
    }//GEN-LAST:event_butndeletebuyActionPerformed

    private void ButnnewprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButnnewprodActionPerformed
        // TODO add your handling code here:
        new NewProduct().setVisible(true);
    }//GEN-LAST:event_ButnnewprodActionPerformed

    private void ButnupdateprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButnupdateprodActionPerformed
        // TODO add your handling code here:
        new UpdateProduct().setVisible(true);
    }//GEN-LAST:event_ButnupdateprodActionPerformed

    private void ButnProductdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButnProductdetActionPerformed
        // TODO add your handling code here:
        new ProductDetails().setVisible(true);
    }//GEN-LAST:event_ButnProductdetActionPerformed

    private void ButndeleteprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButndeleteprodActionPerformed
        // TODO add your handling code here:
        new DeleteProduct().setVisible(true);
    }//GEN-LAST:event_ButndeleteprodActionPerformed

    private void butnbillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butnbillingActionPerformed
        // TODO add your handling code here:
        new Billing().setVisible(true);
    }//GEN-LAST:event_butnbillingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButnBuyerdet;
    private javax.swing.JButton ButnProductdet;
    private javax.swing.JButton ButnUpdateBuy;
    private javax.swing.JButton Butndeleteprod;
    private javax.swing.JButton Butnnewprod;
    private javax.swing.JButton Butnupdateprod;
    private javax.swing.JButton ButtNewB;
    private javax.swing.JLabel NewProd;
    private javax.swing.JLabel Updatebuy;
    private javax.swing.JLabel Updateprod;
    private javax.swing.JLabel bill;
    private javax.swing.JButton butnbilling;
    private javax.swing.JButton butndeletebuy;
    private javax.swing.JButton buttonclose;
    private javax.swing.JButton buttonlogout;
    private javax.swing.JLabel buyerdetail;
    private javax.swing.JLabel closeapp;
    private javax.swing.JLabel deletebuy;
    private javax.swing.JLabel deleteprod;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel newBuy;
    private javax.swing.JLabel productdetail;
    // End of variables declaration//GEN-END:variables
}
